# tmpfiles for CoreTexDB runtime dirs
d /opt/CoreTexDB-V0.2.4/data 0700 coretex coretex -
d /opt/CoreTexDB-V0.2.4/data/logs 0750 coretex adm -
d /opt/CoreTexDB-V0.2.4/data/logs/audit 0750 coretex adm -
d /opt/CoreTexDB-V0.2.4/data/temp 0700 coretex coretex -
